site_name: ModelSkill documentation
site_url: https://dhi.github.io/modelskill/
theme: 
  name: material
  features:
    - navigation.tabs
    # - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes
  # toc-depth: 1

nav: 
  - User Guide:
    - 'user-guide/index.md'
    - 'getting-started.md'
    - 'user-guide/terminology.md'  
    - 'user-guide/data-structures.md'
    - 'user-guide/matching.md'
    - 'user-guide/plotting.md'
    - 'user-guide/selecting-data.md'
    - 'overview.md'    
  - API Reference:
    - 'api/index.md'
    - Observation:
      - 'api/observation/index.md'
      - observation(): 'api/observation/observation.md'
      - PointObservation: 'api/observation/point.md'
      - TrackObservation: 'api/observation/track.md'        
    - Model Result:
      - 'api/model/index.md'
      - model_result(): 'api/model/model_result.md'
      - PointModelResult: 'api/model/point.md'
      - TrackModelResult: 'api/model/track.md'
      - DfsuModelResult: 'api/model/dfsu.md'
      - GridModelResult: 'api/model/grid.md' 
      - DummyModelResult: 'api/model/dummy.md' 
    - 'api/matching.md'
    - 'api/comparer.md'
    - 'api/comparercollection.md'
    - 'api/metrics.md'
    - 'api/skill.md'
    - 'api/gridded_skill.md'
    - 'api/plotting.md'
    - 'api/settings.md'
    - 'api/quantity.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
repo_name: DHI/modelskill
repo_url: https://github.com/DHI/modelskill
plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options: 
          show_source: true
          separate_signature: true
          inherited_members: true
          show_root_heading: true
          # show_root_toc_entry: false
          show_symbol_type_heading: true
          heading_level: 2
          docstring_style: "numpy" # default is google