site_name: modelskill
repo_url: https://github.com/DHI/modelskill
repo_name: DHI/modelskill

theme: 
  name: material
  features:
    # - navigation.tabs
    # - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.indexes

nav: 
  - 'index.md'
  - 'getting-started.md'
  - 'overview.md'
  - 'vision.md'
  - 'terminology.md'
  - API:
    - 'api/index.md'
    - Observation:
      - 'api/observation/index.md'
      - PointObservation: 'api/observation/point.md'
      - TrackObservation: 'api/observation/track.md'        
    - Model Result:
      - 'api/model/index.md'
      - PointModelResult: 'api/model/point.md'
      - TrackModelResult: 'api/model/track.md'
      - DfsuModelResult: 'api/model/dfsu.md'
      - GridModelResult: 'api/model/grid.md'  
    - 'api/matching.md'
    - 'api/comparer.md'
    - 'api/comparercollection.md'
    - 'api/metrics.md'
    - 'api/skill.md'
    - 'api/gridded_skill.md'
    - 'api/plotting.md'
    - 'api/settings.md'
    - 'api/quantity.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: True
          inherited_members: True
          show_root_heading: True
          show_symbol_type_heading: True
          heading_level: 2
          docstring_style: "numpy" # default is google