[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name="modelskill"
version="0.9.dev0"
dependencies = [
    "numpy",
    "pandas",
    "mikeio >= 1.2",
    "matplotlib",
    "xarray",
    "markdown",
    "jinja2", # TODO remove?
]

authors = [
  { name = "Jesper Sandvig Mariegaard", email="jem@dhigroup.com" },
  { name="Henrik Andersson",email="jan@dhigroup.com"},
]
description="Compare results from simulations with observations."
license="MIT"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
]

[project.scripts]
modelskill = "modelskill.cli:report"

[project.optional-dependencies]
dev = ["pytest",
        "sphinx==4.5.0",  # pin version to work with sphinx-book-theme
        "sphinx-book-theme",
        "black==22.3.0",
        "plotly >= 4.5",]

test =  [
            "pytest",
            "netCDF4",
            "openpyxl",
            "dask",
        ]

notebooks = [
            "nbformat",
            "nbconvert",
            "jupyter",
            "plotly",
            "shapely",
        ]

[project.urls]
"Homepage" = "https://github.com/DHI/modelskill"
"Bug Tracker" = "https://github.com/DHI/modelskill/issues"


