project:
  type: website

website:
  title: "ModelSkill"
  page-footer: "© 2024 DHI Group"
  repo-url: https://github.com/DHI/modelskill
  repo-actions: [edit]
  repo-subdir: docs
  page-navigation: true
  
  navbar:
    tools:
    - icon: github
      menu:
      - text: Source Code
        url:  https://github.com/DHI/modelskill
      - text: Report a Bug
        url:  https://github.com/DHI/modelskill/issues
    left:
      - href: index.qmd
        text: Home
      - user-guide/index.md
      - href: examples/index.qmd
        text: Examples
      - href: api/index.qmd
        text: API Reference
  sidebar:
    style: docked
    search: true
    contents: 
      - section: "User Guide"
        href: user-guide/index.md
        contents: 
         - user-guide/getting-started.qmd
         - user-guide/overview.md
         - user-guide/terminology.md
         - user-guide/data-structures.md
         - user-guide/workflow.md
         - user-guide/matching.md
         - user-guide/plotting.qmd
         - user-guide/selecting-data.md
      - section: "Examples"
        href: examples/index.qmd
        contents:
          - href: examples/MIKE21HD_dfsu.qmd  
            text: MIKE21 HD
          - href: examples/Hydrology_Vistula_Catchment.qmd
            text: Hydrology Vistula Catchment
          - href: examples/Metocean_track_comparison.qmd
            text: Metocean track comparison
          - href: examples/Prematched_with_auxiliary.qmd
            text: Prematched with auxiliary

metadata-files:
  - _sidebar.yml

filters:
  - interlinks
interlinks:
  sources:
      xarray: 
        url: https://xarray.pydata.org/en/stable/
      pandas: 
        url: https://pandas.pydata.org/docs/


quartodoc:
  style: pkgdown
  dir: api
  package: modelskill
  renderer:
    style: markdown
    display_name: relative

  sidebar: "_sidebar.yml"

  sections:
    - title: Observation
      desc: ""
      contents:
        - observation
        - PointObservation
        - TrackObservation
    - title: Model Result
      desc: ""
      contents:
        - model_result
        - PointModelResult
        - TrackModelResult
        - DfsuModelResult
        - GridModelResult
        - DummyModelResult
    - title: Matching
      desc: Matching classes and functions
      contents:
        - match
        - from_matched
    - title: Comparer
      desc: ""
      contents:
        - name: Comparer
          members:
            - skill
            - gridded_skill
            - score
            - rename
            - sel
            - where
            - query
            - to_dataframe
            - save
            - load
        -  name : comparison.ComparerPlotter

        - name: ComparerCollection
          members:
            - skill
            - gridded_skill
            - score
            - rename
            - sel
            - save
            - load
        - name : comparison.ComparerCollectionPlotter
        - name: SkillTable
    
    - title: Plotting
      desc: ""
      contents:
      
      - name: plotting
        members: 
          - scatter
          - wind_rose
          - taylor_diagram
          - spatial_overview
          - temporal_coverage
        
    - title: Metrics  
      desc: ""
      contents:
        - metrics
    - title: Settings
      desc: ""
      contents:
        - settings
    - title: Quantity
      desc: ""
      contents:
        - Quantity

format:
  html:
    theme: cosmo
    toc: true
