project:
  type: website
  

website:
  title: "ModelSkill"
  page-footer: "© 2024 DHI Group"
  repo-url: https://github.com/DHI/modelskill
  repo-actions: [edit]
  repo-subdir: docs
  page-navigation: true
  navbar:
    tools:
    - icon: github
      menu:
      - text: Source Code
        url:  https://github.com/DHI/modelskill
      - text: Report a Bug
        url:  https://github.com/DHI/modelskill/issues
    left:
      - href: index.qmd
        text: Home
      - user-guide/index.md
      - href: examples/index.md
        text: Examples
      - href: api/index.qmd
        text: API Reference
  sidebar:
    style: docked
    search: true
    contents: 
      - section: "User Guide"
        contents:
         - user-guide/index.md
         - user-guide/getting-started.md
         - user-guide/overview.md
         - user-guide/terminology.md
         - user-guide/data-structures.md
         - user-guide/matching.md
         - user-guide/plotting.md
         - user-guide/selecting-data.md
      - section: "Examples"
        contents:
          - href: examples/index.qmd
            text: Overview
          - href: examples/MIKE21HD_dfsu.qmd  
            text: MIKE21 HD
          - href: examples/Hydrology_Vistula_Catchment.qmd
            text: Hydrology Vistula Catchment
          - href: examples/Metocean_track_comparison.qmd
            text: Metocean track comparison
          - href: examples/Prematched_with_auxiliary.qmd
            text: Prematched with auxiliary

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

quartodoc:
  style: pkgdown
  dir: api
  package: modelskill
  renderer:
    style: markdown
    display_name: relative

  sidebar: "_sidebar.yml"

  sections:
    - title: Observation
      desc: ""
      contents:
        - observation
        - PointObservation
        - TrackObservation
    - title: Model Result
      desc: ""
      contents:
        - model_result
        - PointModelResult
        - TrackModelResult
        - DfsuModelResult
        - GridModelResult
        - DummyModelResult
    - title: Matching
      desc: Matching classes and functions
      contents:
        - matching
    - title: Comparer
      desc: ""
      contents:
        - name: Comparer
          members:
            - skill
            - gridded_skill
            - score
            - rename
            - sel
            - where
            - query
            - to_dataframe
            - save
            - load

        - name: ComparerCollection
          members:
            - skill
            - gridded_skill
            - score
            - rename
            - sel
            - save
            - load
        - name: SkillTable
    
    - title: Comparison plotting
      desc: ""
      contents:
      - comparison._comparer_plotter.ComparerPlotter
      - comparison._collection_plotter.ComparerCollectionPlotter
        
    - title: Metrics  
      desc: ""
      contents:
        - metrics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
