name: Build documentation

on:
  push:
    branches:    
      - main
  pull_request:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Add Fontawesome to Quarto
      run: quarto add quarto-ext/fontawesome
        
    - name: Install modelskill
      run: |
        pip install .[dev]
    
    - name: Quarto build
      run: |
        cd docs
        quartodoc build
        quarto render
