name: Build documentation (don't publish)

on:
  pull_request:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install modelskill
      run: |
        pip install .[dev]
    
    - name: Mkdocs build
      run: mkdocs build

    - name: Deploy to Azure blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name staging --auth-mode login -d '$web' -s site/