name: Build documentation (staging)

on:
  pull_request:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install modelskill
      run: |
        pip install .[dev]
    
    - name: Mkdocs build
      run: mkdocs build

    - name: Add robots.txt
      run: |
        echo -e "User-agent: *\nDisallow: /" > site/robots.txt

    - name: Deploy to Azure blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name staging login -d '$web' -s site/ --sas-token ${{secrets.BLOB_SAS_TOKEN}}