name: Full test

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  build:
    if: github.event.review.state == 'APPROVED'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]      

    steps:
    - uses: actions/checkout@v3
    - uses: chartboost/ruff-action@v1 # Fail fast if there are any linting errors
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        
    - name: Install modelskill
      run: |
        pip install .[test]
    - name: Static type check
      run: make typecheck
    - name: Test with pytest
      run: |
        pytest --cov=modelskill --ignore tests/notebooks/
    - name: Test docstrings with pytest
      run: |
        pytest ./modelskill/metrics.py --doctest-modules
