name: Notebooks test

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: '! github.event.pull_request.draft'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'    
    - name: Install modelskill
      run: |
        pip install .[test,notebooks]    
    - name: Test notebooks    
      run: |
        pytest tests/notebooks/
